version: '3'

volumes:
  owndb:
    driver: "${VOLUME_DRIVER}"
  owncloud_data:
    driver: "${VOLUME_DRIVER}"
  owncloud_apache2:
    driver: "${VOLUME_DRIVER}"
networks:
  owncloud-network:
services:
  owndb:
    container_name: owndb
    image: mysql:${MYSQL_VERSION}
    restart: on-failure:10
    logging:
      driver: "journald"
    ports:
      - "3306:3306"
    networks:
      - owncloud-network
    volumes:
      - owndb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
  owncloud:
    container_name: owncloud
    image: owncloud:${OWNCLOUD_VERSION}
    restart: on-failure:10
    logging:
      driver: "journald"
    ports:
       - "443:443"
       - "80:80"
    depends_on:
       - "owndb"
    networks:
      - owncloud-network
    volumes:
      - owncloud_data:/var/www/html
      - owncloud_apache2:/etc/apache2
