version: '3'

volumes:
  ownmysql:
    driver: "${VOLUME_DRIVER}"
  owncloud1:
    driver: "${VOLUME_DRIVER}"
  owncloud2:
    driver: "${VOLUME_DRIVER}"
networks:
  owncloud-network:
services:
  ownmysql:
    image: mysql
    restart: on-failure:10
    logging:
      driver: "journald"
    ports:
      - "3306:3306"
    networks:
      - owncloud-network
    volumes:
      - ownmysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=owncloud
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=owncloud
  owncloud:
    image: owncloud
    restart: on-failure:10
    logging:
      driver: "journald"
    ports:
       - "443:443"
       - "80:80"
    depends_on:
       - "ownmysql"
    networks:
      - owncloud-network
    volumes:
      - owncloud1:/var/www/html
      - owncloud2:/etc/apache2
