version: '2.1'

volumes:
  ownclouddb:
    driver: "${VOLUME_DRIVER}"
  owncloud_data:
    driver: "${VOLUME_DRIVER}"
  owncloud_apache2:
    driver: "${VOLUME_DRIVER}"
networks:
  owncloud-network:
  front_proxy-network:
services:
  ownclouddb:
    image: mysql:${MYSQL_VERSION}
    restart: unless-stopped 
    logging:
      driver: "journald"
    ports:
      - "3306"
    networks:
      - owncloud-network
    volumes:
      - ownclouddb:/var/lib/mysql
    environment:
       constraint:volume.driver: =${VOLUME_DRIVER}
       MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
       MYSQL_USER: ${MYSQL_USER}
       MYSQL_PASSWORD: ${MYSQL_PASSWORD}
       MYSQL_DATABASE: ${MYSQL_DATABASE}
  owncloud:
    image: owncloud:${OWNCLOUD_VERSION}
    restart: unless-stopped 
    logging:
      driver: "journald"
    ports:
      - "443"
      - "80"
    depends_on:
      - "ownclouddb"
    networks:
      - owncloud-network
    volumes:
      - owncloud_data:/var/www/html
      - owncloud_apache2:/etc/apache2
    environment:
       constraint:volume.driver: =${VOLUME_DRIVER}
  owncloud-proxy:
    image: openfrontier/nginx-etcd:${NGINX_VERSION}
    restart: unless-stopped 
    logging:
      driver: "journald"
    ports:
      - "80"
      - "443"
    depends_on:
      - "ownclouddb"
      - "owncloud"
    networks:
      - owncloud-network
      - front_proxy-network
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
       ETCD_CLIENT_IP: ${ETCD_CLIENT_IP}
       PROJECT_NAME: ${PROJECT_NAME}
